             ### Numpy Crash Course  ####

In [2]:
import numpy as np
np.__version__

'2.1.3'

In [88]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [4]:
type(my_list)

list

In [89]:
arr=np.array(my_list)

In [6]:
arr

array([0, 1, 2, 3, 4, 5])

In [12]:
type(arr)

numpy.ndarray

In [7]:

type(my_list)


list

In [8]:
print(type(arr))
print(type(my_list))

<class 'numpy.ndarray'>
<class 'list'>


In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(10,20) # n-1 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
np.arange(10,50,5) # max we can pass 3 argument  

array([10, 15, 20, 25, 30, 35, 40, 45])

In [12]:
np.arange(20, 10)

array([], dtype=int64)

In [13]:
np.arange(-20, 10) # arange funcation fisrt argument always lower than 2nd argument 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [14]:
np.zeros(3) #1D array (parameter tunning)

array([0., 0., 0.])

In [15]:
np.zeros(3, dtype=int) #1D array hyperparameter tunning  

array([0, 0, 0])

In [16]:
np.zeros(3, dtype=float)

array([0., 0., 0.])

In [17]:
np.zeros([2,2]) #2d Array

array([[0., 0.],
       [0., 0.]])

In [18]:
np.zeros([10,10]) #nd Array 

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
np.ones(4,2)

TypeError: Cannot interpret '2' as a data type

In [20]:
np.ones(4, dtype=int)

array([1, 1, 1, 1])

In [21]:
#Rand
#np.random.rand() --> Every time generate float value
#np.random.randint() --> Every time generate it will generate int value


In [22]:
np.random.rand(3)

array([0.06053593, 0.98300303, 0.3298615 ])

In [23]:
np.random.rand(3,4)

array([[0.58879901, 0.85451628, 0.53830837, 0.1575899 ],
       [0.40590274, 0.98913571, 0.93705193, 0.93028711],
       [0.97315956, 0.66295794, 0.18560974, 0.32407556]])

In [24]:
np.random.randint(3) # int generate between range 0-3 (n-1 is applicable ) 3,0

0

In [25]:
np.random.randint(10,20)

13

In [26]:
np.random.randint(10,20, 3) # Generate random number between 10-20, 3 number 

array([12, 14, 11])

In [27]:
ran=np.random.randint(1,10, 4)
print(ran)

[3 3 7 1]


In [28]:
print(np.random.randint(1,10, 4)) # OTP number generation 

[6 5 1 3]


In [29]:
print(np.random.randint(10,40,(10,10))) # 10 by 10 matrix, 10*10mmatrix ==100box and generate the value between 10 to 40
 

[[31 26 20 24 14 36 35 33 14 29]
 [31 21 29 18 22 12 12 33 35 26]
 [29 25 28 10 37 11 35 30 37 32]
 [37 39 13 37 32 29 13 34 36 27]
 [25 32 35 23 31 12 12 22 26 10]
 [23 16 12 14 26 38 13 18 19 26]
 [10 21 17 12 36 15 32 23 20 17]
 [21 10 26 18 18 33 11 14 16 29]
 [34 25 28 38 10 37 23 11 27 19]
 [14 19 35 24 10 32 13 19 11 18]]


In [30]:
print(np.random.randint(1,10,(10,10)))

[[3 7 4 4 3 2 1 2 6 7]
 [2 5 9 5 5 6 7 4 5 3]
 [7 8 1 3 2 4 7 2 6 8]
 [8 1 7 2 2 7 4 9 8 6]
 [7 7 5 5 5 8 8 1 5 5]
 [3 8 9 4 9 2 9 8 2 5]
 [5 4 7 7 9 9 8 5 9 4]
 [8 3 1 8 2 4 1 6 5 2]
 [1 5 9 7 2 8 9 6 9 9]
 [2 9 7 4 7 4 6 2 6 8]]


In [31]:
m=np.random.randint(1,10,(4,6))
print(m)

[[6 4 2 9 6 4]
 [1 6 2 2 2 6]
 [4 1 8 9 2 1]
 [3 8 1 8 1 7]]


In [ ]:
#indexing & slicing in array

In [32]:
print(m)

[[6 4 2 9 6 4]
 [1 6 2 2 2 6]
 [4 1 8 9 2 1]
 [3 8 1 8 1 7]]


In [33]:
m[0]

array([6, 4, 2, 9, 6, 4])

In [34]:
m[0]=[2,6,9,5,9,4] # Array manupulation 

In [35]:
m

array([[2, 6, 9, 5, 9, 4],
       [1, 6, 2, 2, 2, 6],
       [4, 1, 8, 9, 2, 1],
       [3, 8, 1, 8, 1, 7]])

In [36]:
m[2]

array([4, 1, 8, 9, 2, 1])

In [37]:
print(m[0,4])

9


In [38]:
print((m[0,4]), (m[0,5]))

9 4


In [39]:
print(m[-2,-3])

9


In [40]:
m

array([[2, 6, 9, 5, 9, 4],
       [1, 6, 2, 2, 2, 6],
       [4, 1, 8, 9, 2, 1],
       [3, 8, 1, 8, 1, 7]])

In [41]:
len(m) # len function alway generate rows.. len() --count no of rows

4

In [42]:
m.shape #dimension of the array .shape dimension(rows * column) of an array 

(4, 6)

In [43]:
m


array([[2, 6, 9, 5, 9, 4],
       [1, 6, 2, 2, 2, 6],
       [4, 1, 8, 9, 2, 1],
       [3, 8, 1, 8, 1, 7]])

In [44]:
m[:]

array([[2, 6, 9, 5, 9, 4],
       [1, 6, 2, 2, 2, 6],
       [4, 1, 8, 9, 2, 1],
       [3, 8, 1, 8, 1, 7]])

In [65]:
m[0]

array([2, 6, 9, 5, 9, 4])

In [66]:
m[0:4]

array([[2, 6, 9, 5, 9, 4],
       [1, 6, 2, 2, 2, 6],
       [4, 1, 8, 9, 2, 1],
       [3, 8, 1, 8, 1, 7]])

In [72]:
m1=np.random.randint(1,10,(9,9))
print(m1)


[[4 3 6 7 9 7 5 9 9]
 [2 6 7 6 8 8 8 2 9]
 [5 6 6 3 7 1 2 5 6]
 [7 3 4 1 2 7 6 3 4]
 [8 3 3 9 9 6 2 4 8]
 [8 8 6 7 1 8 4 9 8]
 [3 1 7 5 6 1 3 1 1]
 [3 5 4 5 7 6 4 3 5]
 [4 5 1 9 9 1 4 3 1]]


In [76]:
m1[0:9:2]  #Step slicing in array

array([[4, 3, 6, 7, 9, 7, 5, 9, 9],
       [5, 6, 6, 3, 7, 1, 2, 5, 6],
       [8, 3, 3, 9, 9, 6, 2, 4, 8],
       [3, 1, 7, 5, 6, 1, 3, 1, 1],
       [4, 5, 1, 9, 9, 1, 4, 3, 1]])

In [79]:
m1[::2] #print every 2 line after 1st row

array([[4, 3, 6, 7, 9, 7, 5, 9, 9],
       [5, 6, 6, 3, 7, 1, 2, 5, 6],
       [8, 3, 3, 9, 9, 6, 2, 4, 8],
       [3, 1, 7, 5, 6, 1, 3, 1, 1],
       [4, 5, 1, 9, 9, 1, 4, 3, 1]])

In [80]:
m1[::5] #print every 5 line 

array([[4, 3, 6, 7, 9, 7, 5, 9, 9],
       [8, 8, 6, 7, 1, 8, 4, 9, 8]])

In [81]:
m1[::-1]# Reverse the array 

array([[4, 5, 1, 9, 9, 1, 4, 3, 1],
       [3, 5, 4, 5, 7, 6, 4, 3, 5],
       [3, 1, 7, 5, 6, 1, 3, 1, 1],
       [8, 8, 6, 7, 1, 8, 4, 9, 8],
       [8, 3, 3, 9, 9, 6, 2, 4, 8],
       [7, 3, 4, 1, 2, 7, 6, 3, 4],
       [5, 6, 6, 3, 7, 1, 2, 5, 6],
       [2, 6, 7, 6, 8, 8, 8, 2, 9],
       [4, 3, 6, 7, 9, 7, 5, 9, 9]])

In [84]:
m1[::-2]

array([[4, 5, 1, 9, 9, 1, 4, 3, 1],
       [3, 1, 7, 5, 6, 1, 3, 1, 1],
       [8, 3, 3, 9, 9, 6, 2, 4, 8],
       [5, 6, 6, 3, 7, 1, 2, 5, 6],
       [4, 3, 6, 7, 9, 7, 5, 9, 9]])

In [85]:
m1[::2]

array([[4, 3, 6, 7, 9, 7, 5, 9, 9],
       [5, 6, 6, 3, 7, 1, 2, 5, 6],
       [8, 3, 3, 9, 9, 6, 2, 4, 8],
       [3, 1, 7, 5, 6, 1, 3, 1, 1],
       [4, 5, 1, 9, 9, 1, 4, 3, 1]])

In [86]:
m1

array([[4, 3, 6, 7, 9, 7, 5, 9, 9],
       [2, 6, 7, 6, 8, 8, 8, 2, 9],
       [5, 6, 6, 3, 7, 1, 2, 5, 6],
       [7, 3, 4, 1, 2, 7, 6, 3, 4],
       [8, 3, 3, 9, 9, 6, 2, 4, 8],
       [8, 8, 6, 7, 1, 8, 4, 9, 8],
       [3, 1, 7, 5, 6, 1, 3, 1, 1],
       [3, 5, 4, 5, 7, 6, 4, 3, 5],
       [4, 5, 1, 9, 9, 1, 4, 3, 1]])

In [91]:
arr

array([0, 1, 2, 3, 4, 5])

In [92]:
arr.shape

(6,)

In [97]:
arr.reshape(3,2) #

array([[0, 1],
       [2, 3],
       [4, 5]])

In [105]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [106]:
arr.reshape(4,2)

ValueError: cannot reshape array of size 6 into shape (4,2)

In [107]:
arr.reshape(2,3) #

array([[0, 1, 2],
       [3, 4, 5]])

In [110]:
arr.reshape(6,1) #

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [111]:
m # when you see , -- indicare specific value to row and column 

array([[2, 6, 9, 5, 9, 4],
       [1, 6, 2, 2, 2, 6],
       [4, 1, 8, 9, 2, 1],
       [3, 8, 1, 8, 1, 7]])

In [112]:
m[2,4] # slicing only n-1 in right side 

np.int64(2)

In [ ]:
## By default 1st number always belongs to rows 2nd value always belongs to column
## m[Row : Cloumn]

In [113]:
m[:,0]

array([2, 1, 4, 3])

In [117]:
m[:,-3]

array([5, 2, 9, 8])

In [118]:
m1

array([[4, 3, 6, 7, 9, 7, 5, 9, 9],
       [2, 6, 7, 6, 8, 8, 8, 2, 9],
       [5, 6, 6, 3, 7, 1, 2, 5, 6],
       [7, 3, 4, 1, 2, 7, 6, 3, 4],
       [8, 3, 3, 9, 9, 6, 2, 4, 8],
       [8, 8, 6, 7, 1, 8, 4, 9, 8],
       [3, 1, 7, 5, 6, 1, 3, 1, 1],
       [3, 5, 4, 5, 7, 6, 4, 3, 5],
       [4, 5, 1, 9, 9, 1, 4, 3, 1]])

In [119]:
m1[2:]

array([[5, 6, 6, 3, 7, 1, 2, 5, 6],
       [7, 3, 4, 1, 2, 7, 6, 3, 4],
       [8, 3, 3, 9, 9, 6, 2, 4, 8],
       [8, 8, 6, 7, 1, 8, 4, 9, 8],
       [3, 1, 7, 5, 6, 1, 3, 1, 1],
       [3, 5, 4, 5, 7, 6, 4, 3, 5],
       [4, 5, 1, 9, 9, 1, 4, 3, 1]])

In [121]:
m1[:,4]

array([9, 8, 7, 2, 9, 1, 6, 7, 9])

In [122]:
m1[1:4, 1:3]

array([[6, 7],
       [6, 6],
       [3, 4]])

In [123]:
m1[3:8, 3:8]

array([[1, 2, 7, 6, 3],
       [9, 9, 6, 2, 4],
       [7, 1, 8, 4, 9],
       [5, 6, 1, 3, 1],
       [5, 7, 6, 4, 3]])

## Masking or filter in matrix 

In [124]:
m1

array([[4, 3, 6, 7, 9, 7, 5, 9, 9],
       [2, 6, 7, 6, 8, 8, 8, 2, 9],
       [5, 6, 6, 3, 7, 1, 2, 5, 6],
       [7, 3, 4, 1, 2, 7, 6, 3, 4],
       [8, 3, 3, 9, 9, 6, 2, 4, 8],
       [8, 8, 6, 7, 1, 8, 4, 9, 8],
       [3, 1, 7, 5, 6, 1, 3, 1, 1],
       [3, 5, 4, 5, 7, 6, 4, 3, 5],
       [4, 5, 1, 9, 9, 1, 4, 3, 1]])

In [125]:
m1.shape

(9, 9)

In [126]:
id(m1)

5636287504

In [127]:
type(m1)

numpy.ndarray

In [129]:
m1<5

array([[ True,  True, False, False, False, False, False, False, False],
       [ True, False, False, False, False, False, False,  True, False],
       [False, False, False,  True, False,  True,  True, False, False],
       [False,  True,  True,  True,  True, False, False,  True,  True],
       [False,  True,  True, False, False, False,  True,  True, False],
       [False, False, False, False,  True, False,  True, False, False],
       [ True,  True, False, False, False,  True,  True,  True,  True],
       [ True, False,  True, False, False, False,  True,  True, False],
       [ True, False,  True, False, False,  True,  True,  True,  True]])

In [130]:
m1[m1 < 5]

array([4, 3, 2, 2, 3, 1, 2, 3, 4, 1, 2, 3, 4, 3, 3, 2, 4, 1, 4, 3, 1, 1,
       3, 1, 1, 3, 4, 4, 3, 4, 1, 1, 4, 3, 1])

In [131]:
m1[m1 <= 5]

array([4, 3, 5, 2, 2, 5, 3, 1, 2, 5, 3, 4, 1, 2, 3, 4, 3, 3, 2, 4, 1, 4,
       3, 1, 5, 1, 3, 1, 1, 3, 5, 4, 5, 4, 3, 5, 4, 5, 1, 1, 4, 3, 1])

In [132]:
m1[m1 != 5]

array([4, 3, 6, 7, 9, 7, 9, 9, 2, 6, 7, 6, 8, 8, 8, 2, 9, 6, 6, 3, 7, 1,
       2, 6, 7, 3, 4, 1, 2, 7, 6, 3, 4, 8, 3, 3, 9, 9, 6, 2, 4, 8, 8, 8,
       6, 7, 1, 8, 4, 9, 8, 3, 1, 7, 6, 1, 3, 1, 1, 3, 4, 7, 6, 4, 3, 4,
       1, 9, 9, 1, 4, 3, 1])

In [133]:
m1[m1 == 5]

array([5, 5, 5, 5, 5, 5, 5, 5])

In [ ]:
# Numpy 1st crash course Completed 